
project_id = "znaextoidbxrhedufxpc"
api_url = "https://znaextoidbxrhedufxpc.supabase.co"
db_url = "postgresql://postgres:postgres@db.znaextoidbxrhedufxpc.supabase.co:5432/postgres"

[functions.ai-coach]
verify_jwt = true
